---
- name: Crear usuario de dominio vía PowerShell
  hosts: windows
  gather_facts: no

  vars_prompt:
    - name: "usuario"
      prompt: "Introduce el nombre de usuario (sAMAccountName)"
      private: no

    - name: "nombre_completo"
      prompt: "Introduce el nombre completo del usuario"
      private: no

    - name: "contrasena"
      prompt: "Introduce la contraseña inicial"
      private: yes

  tasks:
    - name: Crear usuario en Active Directory con PowerShell
      win_shell: |
        $password = ConvertTo-SecureString "{{ contrasena }}" -AsPlainText -Force
        New-ADUser `
          -Name "{{ nombre_completo }}" `
          -SamAccountName "{{ usuario }}" `
          -AccountPassword $password `
          -Enabled $true `
          -Path "CN=Users,DC=cictest-ansible,DC=local" `
          -PasswordNeverExpires $true `
          -ChangePasswordAtLogon $false
      register: resultado

    - name: Mostrar salida de PowerShell
      debug:
        var: resultado.stdout_lines
